### ISSUE TITLE
-G flag throwing ptxas compilation error

### ISSUE THREAD

**Issue by jasneetsinghwahan** [siboehm/SGEMM_CUDA#4]
Hi,
When I try to compile it using the command:

> mkdir build && cd build && cmake .. && cmake --build .

it compiles and runs.. 

however I couldn't understand the code beginning kernel 2 and hence wanted to run cuda-gdb to see how rows and columns are being accessed, so when I run

> mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug && cmake --build .

it throws an error:

> ptxas /tmp/tmpxft_00004480_00000000-6_runner.ptx, line 881; fatal   : Parsing error near '': syntax error
> ptxas fatal   : Ptx assembly aborted due to errors
> gmake[2]: *** [CMakeFiles/sgemm.dir/build.make:90: CMakeFiles/sgemm.dir/src/runner.cu.o] Error 255
> gmake[2]: Leaving directory '/home/jasneetsingh/Desktop/cuda_experiments/SGEMM_CUDA/build'

something to do with -G flag, but couldn't figure out

this is the last command line executed before the error message:

> /usr/local/cuda-12.3/bin/nvcc -forward-unknown-to-host-compiler $(CUDA_DEFINES) $(CUDA_INCLUDES) $(CUDA_FLAGS) -MD -MT CMakeFiles/sgemm.dir/src/runner.cu.o -MF CMakeFiles/sgemm.dir/src/runner.cu.o.d -x cu -c /home/jasneetsingh/Desktop/cuda_experiments/SGEMM_CUDA/src/runner.cu -o CMakeFiles/sgemm.dir/src/runner.cu.o

-- The CXX compiler identification is GNU 11.4.0
-- The CUDA compiler identification is NVIDIA 12.3.107
-- Check for working CUDA compiler: /usr/local/cuda-12.3/bin/nvcc - skipped
Found CUDA: /usr/local/cuda-12.3 (found version "12.3")

**Comment by siboehm** [comment]
Without looking deeper into this, I've often found nvcc does weird stuff when you try to build in Debug mode, either failing or straight segfaulting, so I don't use that feature very often. 

I don't know exactly what flags `-DCMAKE_BUILD_TYPE=Debug` turns on, but if I'm trying to debug a kernel I often run it with `-lineinfo` (see [here](https://docs.nvidia.com/cuda/cuda-gdb/index.html#compilation-with-linenumber-information)), which allows you to use the debugger but doesn't turn off all the optimizations (unllike -G)

**Comment by jasneetsinghwahan** [comment]
Thanks @siboehm Robert Crovella at nVidia replied mentioning to remove `-src-in-ptx` and just keep `-G` in the CmakeLists.txt file (root folder, line16, `add_compile_options("$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CUDA>>:-lineinfo;-g>")`)
I was able to put breakpoints inside the kernel

Thanks a lot for quick reply. 

For future readers, i wanted to share this 4-week course from UT-Austin [LaFF-on programming for high performance](https://www.cs.utexas.edu/users/flame/laff/pfhp/week4-matrix-matrix-multiplication-on-GPUs.html) that teaches speed-up of matmul on CPUs. For me, after understanding how blocking works, i was able to appreciate your code better
