### ISSUE TITLE
kernel 1 is written using col (x) as row?  Normal use of row (y) improves perf 10x+....

### ISSUE THREAD

**Issue by lessw2020** [siboehm/SGEMM_CUDA#7]
Hi - first off, thanks for the great blog series on kernels.
I've been writing these kernels from scratch for practice and when I compared my kernel1 vs the current naive kernel1, I found an odd discrepancy and wondering if there is a reason for it.

Specifically, the current naive kernel instead of accessing things using row stride (y * N +x), instead uses col stride (x*N + y).  
I don't understand why this is being done and curious about the logic behind it.
~~~
C[x * N + y] = alpha * tmp + beta * C[x * N + y];
vs expected:
C[y*N + x] = alpha * tmp + beta * C[y * N + x];
~~~

Writing it in what I would consider normal results in a massive perf jump relative to the current code (example 4096 = 339.8 GFlops as is, vs a more usual row stride impl = 3295.8 GFlops):

Anyway, I don't know if that is b/c kernel 2 then uses the same thing (calling cRow but calculating it via x, or col...) to do the coalescing, but very curious what is the reason for using this col indexing instead of usual row stride access in this initial kernel?

Thanks much! 

~~~

1 -  current naive kernel 1:

C[x * N + y] = alpha * tmp + beta * C[x * N + y];

Max size: 4096
dimensions(m=n=k) 128, alpha: 0.5, beta: 3
Average elapsed time: (0.000107) s, performance: (   39.3) GFLOPS. size: (128).
dimensions(m=n=k) 256, alpha: 0.5, beta: 3
Average elapsed time: (0.000208) s, performance: (  161.5) GFLOPS. size: (256).
dimensions(m=n=k) 512, alpha: 0.5, beta: 3
Average elapsed time: (0.000816) s, performance: (  329.0) GFLOPS. size: (512).
dimensions(m=n=k) 1024, alpha: 0.5, beta: 3
Average elapsed time: (0.006492) s, performance: (  330.8) GFLOPS. size: (1024).
dimensions(m=n=k) 2048, alpha: 0.5, beta: 3
Average elapsed time: (0.051784) s, performance: (  331.8) GFLOPS. size: (2048).
dimensions(m=n=k) 4096, alpha: 0.5, beta: 3
Average elapsed time: (0.404441) s, performance: (  339.8) GFLOPS. size: (4096).

2 - Normal row:
C[y*N + x] = alpha * tmp + beta * C[y * N + x];


Running kernel 1 on device 0.
Max size: 4096
dimensions(m=n=k) 128, alpha: 0.5, beta: 3
Average elapsed time: (0.000015) s, performance: (  284.6) GFLOPS. size: (128).
dimensions(m=n=k) 256, alpha: 0.5, beta: 3
Average elapsed time: (0.000027) s, performance: ( 1257.9) GFLOPS. size: (256).
dimensions(m=n=k) 512, alpha: 0.5, beta: 3
Average elapsed time: (0.000089) s, performance: ( 3032.7) GFLOPS. size: (512).
dimensions(m=n=k) 1024, alpha: 0.5, beta: 3
Average elapsed time: (0.000659) s, performance: ( 3260.4) GFLOPS. size: (1024).
dimensions(m=n=k) 2048, alpha: 0.5, beta: 3
Average elapsed time: (0.005177) s, performance: ( 3318.4) GFLOPS. size: (2048).
dimensions(m=n=k) 4096, alpha: 0.5, beta: 3
Average elapsed time: (0.041701) s, performance: ( 3295.8) GFLOPS. size: (4096).

**Comment by siboehm** [comment]
Yeah this is just supposed to be educational, which is why for Kernel2 I explain HBM coalescing and then fix this issue :) I think intuitively most people immediately get this correct without thinking about it, but it's still useful to understand why it makes such a big diff and how to not get it wrong accidentally.

**Comment by lessw2020** [comment]
Thank very much @siboehm  - makes sense and appreciate the info!
